'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BookingData
    Public Property id As Integer
    Public Property Service As String
    Public Property Description As String
    Public Property TechName As String
    Public Property ServiceDate As String
    Public Property ServiceTime As String
    Public Property Customer As String
    Public Property Address As String
    Public Property emial As String
    Public Property Phone As String
    Public Property Status As String

End Class
