'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property id As Integer
    Public Property ProductName As String
    Public Property ProductType As String
    Public Property SubCatagoty As String
    Public Property ServiceType As String
    Public Property Cost As String
    Public Property Note As String

End Class
